export interface AdmissionMeritList {
  id?: number;
  name: string;
  description?: string;
  academicYear?: string;
  sessionId?: number;
  session?: any;
  facultyId?: number;
  faculty?: any;
  departmentId?: number;
  department?: any;
  programId?: number;
  program?: any;
  shift?: string;
  quotaType?: string;
  testId?: number;
  test?: any;
  status: string;
  totalSeats?: number;
  totalApplicants?: number;
  selectedCount?: number;
  waitingCount?: number;
  cutoffScore?: number;
  publishedAt?: string;
  publishedBy?: string;
  remarks?: string;
  createdAt?: string;
  updatedAt?: string;
}
